### ISSUE TITLE
TypeError: Object(...) is not a function with Angular 

### ISSUE THREAD

**Issue by simeyla** [cartant/rxjs-etc#52]
I had all kinds of issues today with `rxjs@6.5.2` and `rxjs-etc@9.5.0` with the error:

   TypeError: Object(...) is not a function with Angular 

I was only using `endWith` and `pairwiseStartWith` - which were easy to remove. I wasn't even deliberately using `endWith` from your library - it just decided to autocomplete it a while back.

Anyway I don't know if there's an incompatibility with the 9.5.0 library - but everything magically worked when I removed the code.

The odd thing was my browser completely locked up and that made everything super hard to debug. Just wanted to point it out in case it's obvious to you what happened - it's not holding me up anymore but wanted to pass it on.

**Comment by cartant** [comment]
Without knowing more about what it was that you did, I don't see what I can do here. There is no obvious problem that I can see. The tests all pass with the latest version of RxJS, AFAICT.
