### ISSUE TITLE
[Feature] doOnSubscribe

### ISSUE THREAD

**Issue by libinvarghese** [cartant/rxjs-etc#53]
Could you please add the `doOnSubscribe` operator?

The `doOnSubscribe` operator registers an Action which will be called whenever an observer subscribes to the Observable.

I use this gist separately - https://gist.github.com/evxn/750702f7c8e8d5a32c7b53167fe14d8d

It would be great to see this operator as part of this library.

Additional Reference: [StackOverflow: Observable.onSubscribe equivalent in RxJs](https://stackoverflow.com/questions/41883339/observable-onsubscribe-equivalent-in-rxjs)

**Comment by cartant** [comment]
Hmm. Maybe, but I'd probably call it `tapSubscribe`.

What's the use case? If it's just for debugging, or it's not something that needs to be done often, you can inline `defer`:

```ts
source.pipe(
  ob => defer(() => console.log("subscribed") && ob)
)
```

**Comment by cartant** [comment]
There's a `tapSubscribe` in 9.6.0 that will allow you to tap into subscription and unsubscription. See the tests.
