### ISSUE TITLE
npm distribution is missing package.json files for import locations

### ISSUE THREAD

**Issue by lukk84** [cartant/rxjs-etc#55]
There is some issue with npm distribution. Latest published version 9.6.1 is still missing package.json files for operators, observable and schedulers.

My best guess is that there is problem with `dist:copy` goal and `cpy **/package.json ../dist/ --cwd=source/ --parents`

I've tested it locally but maybe it behaves differently on build server.

**Comment by cartant** [comment]
I don't think it will have had anything to do with the command. I've use exactly that command in other packages. I've re-published it - as 9.6.2 - and according to what npm logs out, the archive should contain the `package.json` files.

**Comment by lukk84** [comment]
It's ok now, thanks!
