### ISSUE TITLE
Update rxjs-report-usage dependency

### ISSUE THREAD

**Issue by antikaspar** [cartant/rxjs-etc#93]
Hello @cartant,
could you update the `rxjs-report-usage` dependency to 1.0.6 to incorporate the latest patches (e.g. `prompts`)?

Thanks in advance

**Comment by cartant** [comment]
I don't see why any change would be necessary, as `~1.0.4` matches the latest version and the lock file is not included in the distribution.

**Comment by antikaspar** [comment]
Thank you. My mistake. Still learning semver
