### ISSUE TITLE
Change rxjs-report-usage to devDependency

### ISSUE THREAD

**Issue by dobesv** [cartant/rxjs-etc#94]
It seems like `rxjs-report-usage` is a command-line tool intended to be run be a developer if they so choose.

Having it as a runtime dependency adds a bunch of unnecessary code to deployed code.  

The tool depends on babel which is a pretty big package, so it's more than just the little script itself, but also a decent chunk of babel

**Comment by cartant** [comment]
I've removed it entirely in 10.6.2.
